### ISSUE TITLE
NullPointerException in Eval

### ISSUE THREAD

**Issue by burdoto** [comroid-git/Cobalton#7]
![grafik](https://user-images.githubusercontent.com/42473485/68122408-8fdea600-ff0a-11e9-9407-9e810135468e.png)

**Comment by burdoto** [comment]
zitat auri: "viel spaß jay"

**Comment by peanutbother** [comment]
This might have to do with CompletableFuture -> Result 
if Result is already completed.

EvalFactory or EvalEmbed generally needs refactoring.

**Comment by burdoto** [comment]
```
14:24:37.395 [Javacord - Central ExecutorService - 2] ERROR de.comroid.javacord.util.commands.CommandHandler - Catching
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_222]
	at org.javacord.core.util.rest.RestRequest.lambda$execute$0(RestRequest.java:270) ~[javacord-core-3.0.5-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_222]
	at org.javacord.core.util.ratelimit.RatelimitManager.handleResponse(RatelimitManager.java:197) ~[javacord-core-3.0.5-SNAPSHOT.jar:?]
	at org.javacord.core.util.ratelimit.RatelimitManager.lambda$queueRequest$2(RatelimitManager.java:129) ~[javacord-core-3.0.5-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at de.comroid.eval.model.EvalViewer.complete(EvalViewer.java:120) ~[javacord-utilities-1.1.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_222]
	... 15 more
```

**Comment by burdoto** [comment]
Moved to https://youtrack.comroid.de/issue/COB-3
